### ISSUE TITLE
Does not appear to work atm?

### ISSUE THREAD

**Issue by kristian-elder** [prometheus-community/json_exporter#3]
I would love to use this, but does not appear to build atm? (Running on Linux Mint 17.3, 64 bit intel)

```
# github.com/Sirupsen/logrus
build/src/github.com/Sirupsen/logrus/logger.go:32: undefined: sync.Pool
# github.com/prometheus/client_golang/prometheus
build/src/github.com/prometheus/client_golang/prometheus/registry.go:450: syntax error: unexpected range, expecting {
build/src/github.com/prometheus/client_golang/prometheus/registry.go:564: non-declaration statement outside function body
build/src/github.com/prometheus/client_golang/prometheus/registry.go:565: non-declaration statement outside function body
build/src/github.com/prometheus/client_golang/prometheus/registry.go:566: syntax error: unexpected }
```

**Comment by kawamuray** [comment]
@kristian-elder Hmm, looks like these errors are happening when `go get`ting https://github.com/Sirupsen/logrus and https://github.com/prometheus/client_golang .

However I could build this on `CentOS 7.1` with go version `go version go1.4.2 linux/amd64
` w/o an error.

Can you check which version of `go` are you using now?(`go version`)
Also, try clearing `./build` directory to remove broken source code cache for just in case.

**Comment by kristian-elder** [comment]
Thanks!

I don't have access to that machine right now, but tested on "go version go1.6 linux/amd64", and all working. Being new to go, I incorrectly assumed that the gow wrapper would pull a specific version of the go stack (much as gradlew would of gradle etc).

**Comment by jnbnyc** [comment]
This works on `CentOS Linux release 7.3.1611 // go version go1.7.5 linux/amd64`

```bash
$ go get github.com/kawamuray/prometheus-json-exporter
```

Just make sure to set GOPATH before.

Thanks for this @kawamuray

**Comment by SuperQ** [comment]
This should now be working. Builds are automated and tested in master via CI.
